### ISSUE TITLE
Autodiscover of games and applications

### ISSUE THREAD

**Issue by jacksonsoftwareio** [jacobpalm/costa#17]
It could be very cool, if Costa GUI could do some kind of autodiscover of games and applications.

**Comment by jacobpalm** [comment]
Interesting idea, and definitely a boost to usability. I will look into this.

**Comment by jacksonsoftwareio** [comment]
Cool Jacob - I'm looking forward to see what you may come up with :)

**Comment by jacksonsoftwareio** [comment]
Any update on this feature Jacob? 😀

**Comment by jacobpalm** [comment]
I'm considering adding a new accessory for this purpose, one that could track a list of either known games/programs and present them to the user, or one that just finds all application files on disk. And then allow the user to select which ones to add to the desktop.

I'll get back to you on this soon.

**Comment by Axle-Ozz-i-sofT** [comment]
Hi [@jacobpalm](https://github.com/jacobpalm), [jacksonsoftwareio](https://github.com/jacksonsoftwareio)
If I may suggest, Auto adding bat, com, exe can be as much work as manually adding a link to an application. When we consider the number of executable files in a single install it creates a great many files to "Eliminate" from the list of found executables. By the time we eliminate the apps we don't want we could have already expended the time to add the apps we do want :)
I have seen and used this feature with a number of other launch menu system in the past and they have never really seamed successful and the auto search for apps was dropped. I can't recall which menu systems had it as the feature has long gone. It could have bean one of the early lupo (a-suite), P-apps type launchers.
>
I am working a similar problem myself atm between creating an application catalog from a CD-ROM or dir. I can scan an entire dir or drive to a list of files, but I still have to manually organize categories and descriptions. Categories become the biggest hurdle as many categories cross over and can link to a single file where my directory archives currently have a lot of duplicates.
>
Either way, Costa desktop is my favorite application along side of File Maven 3 :)

**Comment by BillDStrong** [comment]
You can automate the categorizing a bit by using the different game databases online. I don't think there is anything similar for other applications, but it would allow you to separate the games from everything else.

**Comment by jacobpalm** [comment]
After consideration, I've decided not to implement an autodiscover feature. As some have pointed out, just detecting all exe and com files would result in a lot of icons being added, requiring manual cleanup. Adding a database of known apps and games would also take a fair amount of work. Since Costa got a file browsing dialog, it has become much easier to locate programs when adding icons, and I think that kind of negates the need for auto discovery - although it would be a nice feature, I agree.
