### ISSUE TITLE
Dropdown menu with all shortcuts

### ISSUE THREAD

**Issue by jacksonsoftwareio** [jacobpalm/costa#18]
The icon support on the desktop is limited to 27 icons, as far as I can remember.
I was thinking, something like a dropdown menu from the top panel, with all the shortcuts - and the ones that the desktop could not display. From there it could be be easy and fast to start up a program, without looking for the icon

**Comment by jacobpalm** [comment]
Good idea - I will examine possible solutions for this.

Until I find the time to implement something, you can turn of the display of link locations in the settings to make icon captions more compact, thus allowing for more icons on scren.
The desktop is not limited to 27 icons per se, but using the default layout and spacing of icons, that is what will fit visually on the screen without icons overlapping.
