### ISSUE TITLE
Costa Installer

### ISSUE THREAD

**Issue by jacksonsoftwareio** [jacobpalm/costa#20]
How about the Costa Shell got some kind of easy, no-hassle program installer, to make it easy to install games and programs into the DOS system?

I mean, when I download a zipfile, from myabandonware.com, its would be very nice, just to let Costa do the "installation" and the creation of the desktop shortcut :-)

Costa could have some built-in recognition of known programs and games, which could be used to autosetup the desktop shortcut with the right icon and name.
It the build-in logic can not recognize a program, it should create shortcuts the whatever .exe, .com and .bat file it finds in the zipfile.

**Comment by Axle-Ozz-i-sofT** [comment]
Hi,
This is another DOS problem I am working in the background and relates to the "Auto add applications" suggestion. DOS didn't have much of a standard when it came to application locations. Even pif files can end up in multiple locations.
At the moment I am launching ALL applications from a BAT either in the system\DOS directory or the application directory. I am considering moving all application start up BAT file to a single "Launch", "Appstart" or some similar named directory in my future DOS install and adding the bat directory to the system path.
My current FreeDOS install uses a base config.sys(with boot menu) and autoexec.bat to set base paths and drivers.
I then run a basic launch menu after autoexec to load the shell/launcher I want to use I don't load any custom path environments here.
Either from Costa or File Maven 3 I then run the batch file for the individual application where I have to set specific environment variables in the bat for that application. ALL apps run from a batch file.
If I move all of those batch files to a single directory and set the path to it in autoexec I can then launch the application name.bat form any directory without the fully qualified path.
>
I think the question is" "Where do I install an application to?" as DOS had no "Program Files" directory. I currently use C:\PROGS as my default for manual installs, but many installers will go to root and some other variety of locations. Even FreeDOS fdimples uses a number of different program directories including C:\PROGS.
>
The other issue is stopping app installers from altering my config.sys and autoexec.bat by adding it's own environment variable and paths. 

DOS is messy, but I love it lol
Axle
