### ISSUE TITLE
Thanks for Costa

### ISSUE THREAD

**Issue by eersoy93** [jacobpalm/costa#28]
Hi Jacob,

I'm Erdem Ersoy, a hobby software developer. Thank you for your Costa software, I could use my DOS(Box-X) with a GUI.

Best regards from Turkey,
Erdem

**Comment by jacobpalm** [comment]
Thanks Erdem! It's always nice to hear from someone who has found a use for the software I write.
If you have any feedback or requests, feel free to open an issue here and I will see what I can do.
Should you end up creating some themes or icons, these can also be submitted for inclusion in the next version.

Regards from Denmark,
Jacob

**Comment by eersoy93** [comment]
I'm not a grpahic designer but I'm software developer/computer programmer. I could use VBDOS 1.0 for contribute to Costa.
