### ISSUE TITLE
Running Win 3.1 apps in Costa

### ISSUE THREAD

**Issue by dgrtygry** [jacobpalm/costa#33]
Will it ever be possible for Windows 3.1 Apps or Windows 9X apps to run in Costa?

**Comment by jacobpalm** [comment]
Hi dgrtygry,

No, that would be a massive undertaking as Windows apps require tremendous amounts of APIs to be implemented. No one-man project would be able to accomplish this, and it's just not technically feasible in the BASIC language.

**Comment by dgrtygry** [comment]
Ok.
