### ISSUE TITLE
Start menu or some sort of Application launcher?

### ISSUE THREAD

**Issue by dgrtygry** [jacobpalm/costa#34]
Could you implement some sort of Application launcher into Costa? And can Costa have some sort of taskbar or a panel to place apps on?

**Comment by jacobpalm** [comment]
Hi dgrtygry,

The desktop is the application launcher, I'm not sure what you would like to see? The taskbar/panel idea is nice, but since Costa doesn't have multitasking, I don't really see a use for it.

If you can expand on your thoughts, maybe I can look in to something.
