### ISSUE TITLE
Font Format Convert

### ISSUE THREAD

**Issue by EricZhang5077** [jacobpalm/costa#37]
Hello! Costa's graphical interface is perfect and shocks me! Rarely seen on DOS. 
However, I have a small problem in using it, the fonts in the GUI do not display properly on my computer. 
I have looked at the Font files located in the DATA directory, how can I convert the regular TTF, OTF files to the formats supported by Cosat?

**Comment by jacobpalm** [comment]
Hello Eric! Thank you for the kind words, it's good motivation to keep going.

The font files for Costa are an odd format, not something that can easily be converted to from TTF or other modern formats. Each letter is saved as BASIC DRAW statement commands, along with an integer defining the width of the character (the exception being the fontSystem font, which is monospaced and thus doesn't need width information). It's a homemade format, but the original font files and DRAW statements where made by the Rush team.

Can you describe how the fonts don't display properly? I've tested on a range of both real computers and DOS emulators and have never seen any artifacts in the fonts. If possible, a screenshot or photo of the screen would be helpful in identifying the issue.

**Comment by jacobpalm** [comment]
I have not been able to reproduce the issue, and as such will close it. If you can provide a screenshot or some more information about the fonts not displaying properly, please feel free to reopen the issue and I will happily investigate further.
