### ISSUE TITLE
Update 1.7.4 Thanks

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [jacobpalm/costa#39]
Hi Jacob

Not an issue. Just to say well done on the 1.7.4 update.
Also to say that I have started a guide on setting up FreeDOS (v1.3) along with some ease of use customization's and setting up a handful of different development environments.
Along with Briggs Softworks File Maven (DOS) for file management, Costa is the feature desktop launch system in the guide.
I am looking forward to showcasing Costa with snapshots in the guide and hopefully some related video guides. Costa 1.7.4 will get a good workout in the coming weeks :)
P.S. the previous 1.7.3 is going great in my FD1.3 test install and playground for working out the guide contents :)

Thank you for Costa Desktop. Your efforts are appreciated.
Axle

**Comment by jacobpalm** [comment]
Hi Axle,

Thank you for your feedback! It's always nice to hear that someone has found use for something you've made, so I really appreciate it.

I'm very interested in seeing the guide you're working on, so please be sure to let me know when it's done. I might share news about it on the Costa webpage, and link to it from there.

If you encounter any issues in your testing, or think of something you would like to see included in a future version, just post an issue here and I'll look in to it.

Oh, and thank you for using Costa!

**Comment by Axle-Ozz-i-sofT** [comment]
My pleasure Jacob.
I have to check the new version and change logs before I post. But I was thinking about a practical future feature from my use of 1.7.3.
The ability to copy paste the shortcuts/links between desktops (database files).
I'll create a new post after I have had a good test run with 1.7.4 :)
>
The 2 guides are supplemental to my beginners guide to programming series and introduce the basic setups for DOS development environments in FreeDOS and Win95. I will use Costa as my default desktop launch pad for each environment in FD. Although not very familiar with Visual Basic for DOS I will likely include the setup alongside of other environments. I have some tertiary modules to complete before end of year as well as finish my 3rd book on setting up programming libraries so maybe by January I'll have Draft previews done :)

Have a good day
Axle
