### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by diejuse** [jacobpalm/costa#43]
First, great OS for DOS!
I suggest these additions:
- Create folders on the desktop.
- Being able to put the menu at the bottom (like in Windows).
- Create a Windows 95 style menu.
Thank you for your work.

**Comment by psychicgoldfish** [comment]
Folders would be great. Right now I'm using the different pages to sort my apps, which works fine, but folders are just easier to use (for mouse users).

**Comment by jacobpalm** [comment]
Thanks for the feedback. A Windows 95 style menu is not the kind of user interface I am aiming for, but I will look in to folders on the desktop. I think that should be fairly easy to implement.

**Comment by aazard** [comment]
My 2 cents:
Could "folder" shortcuts not merely be made to cycle to a specific "desktop" using the "profile" feature?

Costa is very light and "bloating" with 9x type features (desktop folders/start menu) starts to push it to the GEOS/New Deal Office 2000/Breadbox Ensemble arena (and these are very stable/mature and already free/actively developed options).

IMHO, Costa may be better suited to target "being stellar lite on requirements".

**Comment by jacobpalm** [comment]
I've decided to keep it as it is - menu at the top, and no folders. Generally I think the 5 pages should be adequate for most use cases, as each page can hold a fair amount of icons. As aazard commented above, one of the goals of Costa is to keep it small and simple, while stile being functional. It's always a balance between those when deciding on new features and enhancements, and in this case, size and simplivity wins.

Thank you very much for your suggestions, though. I always appreciate any feedback!
