### ISSUE TITLE
Incorrect system requirements listed

### ISSUE THREAD

**Issue by aazard** [jacobpalm/costa#45]
**States**:
"A 286 or better CPU (386 recommended)"

**Issue**:
Evidence of Costa GUI running "Flawlessly" on an 8088 XT:
[link](https://youtu.be/CQAqjdJJ6og?t=435)

**Resolution**:
Restate as:
"A 8088 or better CPU (386 recommended)"

**Comment by jacobpalm** [comment]
Thank you for letting me know, I have modified the system requirements accordingly.

**Comment by aazard** [comment]
no problem, I also believe you have EGA vram needs wrond (ega generally shipped with 64kb ram, and upgraded to 128kb...only EGA video mode 10h would need over 64kb in 16-color @ 640x350, modes 0Dh and 0Eh should operate at 16- color @ 640x350 with only 64kb vram needed.

**Therefor a correction to:
"Requires 64kb vram for EGA 16- color @ 640x350" (less if you are also supporting mono/b&w or lower resolutions)
Would also be suggested.**

**Source**: [link](https://extralives.wordpress.com/2013/09/30/graphics-from-the-past-cga-ega-and-vga/)
"Enhanced Graphics Adapter, in 1984. This time, it could display 16 colors at the same time from a total palette of 64 and cranked the maximum resolution up to an eye blistering 640×350. It even enhanced CGA mode with its ability to display 16 colors at once though it wasn’t always a smooth transition. **It was also packed with 64kb of memory**."

Please let my know if I am in error (EGA is a long time ago)

**Comment by jacobpalm** [comment]
Thanks for your input! I've changed the wording to simply list the resolution required, that way it's a bit easier to avoid incorrect requirements as I think not all EGA cards were fully standards compliant at the time. If it can display 640x350 at 16 colors, it will run Costa.
